project:
  type: book
  output-dir: docs

navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Preface"
        href: preface.qmd
book:
  title: "Introduction to AI"
  subtitle: "A case-based approach"
  reader-mode: true

  page-footer:
    left: |
      course under prep.
    right: |
      This course material was built with <a href="https://quarto.org/">Quarto</a> with <a href="https://github.com/hadley/r4ds">r4ds</a> theme.
  
  cover-image: logo.jpg
  favicon: logo.jpg
  site-url: https://mlsquare.github.io/intro2ai
  repo-url: https://github.com/mlsquare/intro2ai
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - preface.qmd
    - index.qmd
    - course.qmd        
    - part: Lectures
      chapters:
        - ./lectures/L00.qmd
        - ./lectures/L01.qmd
        - ./lectures/L02.qmd
        - ./lectures/L03.qmd
        - ./lectures/L05.qmd
    - part: Lab
      chapters:
        - ./notebooks/01-01-Reg-LM-Sim.ipynb
        - ./notebooks/02-01-Class-Logistic-Sim.ipynb
        - ./notebooks/02-02-Class-Logistic-Iris.ipynb
        - ./notebooks/03-01-Clust-Sim-Ch12-ISL.ipynb
        - ./notebooks/03-02-Clust-Real-Ch12-ISL.ipynb
        - ./notebooks/05-01-Perceptron-Class-Iris.ipynb
    
  
format:
  html:
    theme:
    - pulse
    - mlops.scss
    code-link: true
    author-meta: "mlsquare"
    callout-appearance: simple
    number-sections: false
editor: visual