---
title: "Course"
---

You will find below material and schedule for *Introduction to AI: A case-based approach*. This will evolve as the discussion progress.

Note: I use AI/ML/Statistics interchangeably.

### Syllabus & Schedule

::: {style="font-size: 80%;"}
| \#  | Topics                     | Resources                 |     |
|:----|:---------------------------|:--------------------------|:----|
| 01  | Intro to Linear Regression | [L01](./lectures/L01.qmd) |     |
| 02  | tbd                        | tbd                       |     |

: Part-1: Supervised Learning {.striped}
:::

## Datasets

-   sklearn: Browse the [datasets](https://scikit-learn.org/stable/api/sklearn.datasets.html) - quite useful to study different algorithms.
-   UCI ML Repository: Browse [datasets](https://archive.ics.uci.edu/) or programmatically access the datasets with [ucimlrepo](https://github.com/uci-ml-repo/ucimlrepo)
-   OpenML: Browse [datasets](https://openml.github.io/docs/) or programmatically access the datasets with [openML-Python](https://github.com/openml/openml-python). OpenML lets you do many things like running models, submitting them, and hosting them as well - besides providing a nice way to interact with datasets.
-   HuggingFace: One of the significant and most impactful things that have happened to advancing AI is HuggingFace. Browse [datasets](https://www.kaggle.com/datasets) or [install](https://github.com/huggingface/datasets) for programmatic access
-   Kaggle: Browse [datasets](https://www.kaggle.com/datasets). There are many interesting categories like Biology, Sports, Investing, Social Networks, etc.

### References

-   [An Introduction to Statistical Learning](https://www.statlearning.com/). This [repo](https://github.com/JWarmenhoven/ISLR-python) contains the datasets and notebooks to reproduce the figures and complete the Labs in the textbook (the Python version).
-   [Grokking Machine Learning](https://www.manning.com/books/grokking-machine-learning) from Luis Serrano. His youtube channel [Serrano.Academy](https://www.youtube.com/@SerranoAcademy) is loaded with amazing lectures.
-   [ML Engineering](https://www.mlebook.com/wiki/doku.php), Andiry Burkov, 2019, LeanPub

**Advanced**

-   [Elements of Statistical Learning](https://link.springer.com/book/10.1007/978-0-387-84858-7). This [repo](https://github.com/empathy87/The-Elements-of-Statistical-Learning-Python-Notebooks) contains the datasets and notebooks to reproduce the figures and complete the Labs in the textbook. This book is the big brother of the [An Introduction to Statistical Learning](https://www.statlearning.com/).
-   [Dive into Deep Learning](https://d2l.ai/index.html) [Alex Smola](https://alex.smola.org/) et al
-   [Understanding Deep Learning](https://udlbook.github.io/udlbook/) Prof. [Simon Prince](https://www.bath.ac.uk/person/1545883)

[Soma S Dhavala](https://www.linkedin.com/in/somasdhavala/)\
Discussion Anchor